---
title: "Linkage Analysis"
author: "Vaughn Johnson"
date: "5/17/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Link Components

```{r  warning=FALSE, message=FALSE}
library(purrr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(venn)
library(igraph)
library(reshape2)
library(DT)

path_to_src = file.path(here::here(), 'R', 'Linking')
# source(file.path(path_to_src, 'Linker.R'))

load(file=file.path(path_to_src,
                    "FinalClassification",
                    "full_classification.RData"))

load(file=file.path(path_to_src,
                    "FinalClassification",
                    "full_combined_harmonized.RData"))

link_idx = classification$prediction == 'L'
links    = classification$pairs[link_idx, c('id1', 'id2')]
link_graph = graph_from_edgelist(as.matrix(links), directed=F)
linked_ids = groups(components(link_graph, mode="weak"))
linked_ids = linked_ids[unlist(lapply(
    linked_ids, function(x) length(x) > 1))]

linked_sources = lapply(linked_ids,
                        function(x)  combined_harmonized[x, 'source'])

dup_link_idx = unlist(lapply(linked_sources, function(x) any(duplicated(x))))

dup_links      =    linked_ids[ dup_link_idx]
unique_links   = linked_ids[!dup_link_idx]
unique_sources = linked_sources[!dup_link_idx]

sources = unique(combined_harmonized[, 'source'])

for (source in sources) {
    col_name = paste0("in_", source)
    combined_harmonized[col_name] = combined_harmonized[, 'source'] == source
}

collaps_vals = function(x) {
    return(x[!is.na(x)][1])
}

# This would break if the max row wasn't linked to anything
combined_harmonized['person'] = components(link_graph, mode="weak")$membership
```

# Create Race Vector
```{r warning=FALSE}
race_source = combined_harmonized[c('person', 'race', 'source')]
race_source['race'] = !is.na(race_source['race'])

race_vectors = dcast(race_source, person ~ source) %>%
                    unite(vector, c('fe', 'kbp', 'mpv', 'wapo'), sep="")
```

# Display race vector

The order for the vectors is `fe`, `kbp`, `mpv`, and `wapo`. A 1 means a particular
person appeared once in some dataset with a given race. A 0 means they did not.
A 2 means they appeared twice in that dataset, etc.

```{r}
make_freq_table <- function(field, precision) {
    freq_table = plyr::count(field)
    
    freq_table$'proportion' =  freq_table$freq / sum(freq_table$freq)
    freq_table$'proportion' = round(freq_table$'proportion', 2)
    
    freq_table$'cumulative' = cumsum(freq_table$'proportion')
    freq_table$'cumulative' =  round(freq_table$'cumulative', 2)
    
    return(freq_table)
}

display <- function(source, field) {
    return(datatable(make_freq_table(source[,field], 3)))
}

display(race_vectors, 'vector')
```
